services:
  proxy:
    image: nginx
    ports:
      - :80
  db:
    image: mysql:5.7.43
    environment:
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - :3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=test --execute \"SHOW DATABASES;\""
